#baseURL = "https://gomex.me/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Gomex"
copyright = "&copy; 2016. Some rights reserved."
theme = "diary"
googleAnalytics = "UA-111345881-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Conhecimento retido é conhecimento perdido."
enableGitalk = false

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Meu Blog" # will set 'og:site_name'
description = "Conhecimento retido é conhecimento perdido"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Todos posts"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
[[menu.main]]
name = "Mentoria IaC"
pre = "<i class='fa fa-user fa-fw'></i>"
weight = 2
identifier = "mentoriaiac"
url = "/mentoriaiac/"